# docker-compose.yml
version: '3'

services:

  redis:
    image: 'redis'

  pg:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: 'sentry'
      POSTGRES_PASSWORD: 'sentry'
      POSTGRES_DB: 'sentry'

  sentry:
    image: 'sentry:latest'
    depends_on:
      - 'redis'
      - 'pg'
    ports:
      - '9000:9000'
    environment:
      SENTRY_SECRET_KEY: 'theSentrySecretKey'
      SENTRY_POSTGRES_HOST: 'pg'
      SENTRY_POSTGRES_PORT: '5432'
      SENTRY_DB_NAME: 'sentry'
      SENTRY_DB_USER: 'sentry'
      SENTRY_DB_PASSWORD: 'sentry'
      SENTRY_REDIS_HOST: 'redis'

  sentry_worker:
    image: 'sentry:latest'
    depends_on:
      - 'redis'
      - 'pg'
    command: "sentry run worker"
    restart: always
    environment:
      SENTRY_SECRET_KEY: 'theSentrySecretKey'
      SENTRY_POSTGRES_HOST: 'pg'
      SENTRY_POSTGRES_PORT: '5432'
      SENTRY_DB_NAME: 'sentry'
      SENTRY_DB_USER: 'sentry'
      SENTRY_DB_PASSWORD: 'sentry'
      SENTRY_REDIS_HOST: 'redis'

  sentry_cron:
    image: 'sentry:latest'
    depends_on:
      - 'redis'
      - 'pg'
    command: "sentry run cron"
    restart: always
    environment:
      SENTRY_SECRET_KEY: 'theSentrySecretKey'
      SENTRY_POSTGRES_HOST: 'pg'
      SENTRY_POSTGRES_PORT: '5432'
      SENTRY_DB_NAME: 'sentry'
      SENTRY_DB_USER: 'sentry'
      SENTRY_DB_PASSWORD: 'sentry'
      SENTRY_REDIS_HOST: 'redis'